#!/bin/sh

defaults write -g ApplePressAndHoldEnabled -bool false
defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1
defaults write NSGlobalDomain KeyRepeat -int 0
defaults write com.apple.Finder FXPreferredViewStyle Nlsv
chflags nohidden ~/Library
