ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.oh-my-zsh-custom
ZSH_THEME="zsol"
COMPLETION_WAITING_DOTS="true"
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root)
plugins=(git git-flow django osx virtualenvwrapper encode64 brew zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

unsetopt correct_all
unsetopt nomatch

_Z_NO_RESOLVE_SYMLINKS=1
source $HOME/z/z.sh

# shortcut to this dotfiles path is $DOTFILES
export DOTFILES=$HOME/.dotfiles

# source every .zsh file in this rep
for config_file ($DOTFILES/**/*.zsh); do
  if ! echo $config_file | fgrep -q oh-my-zsh-custom.symlink; then
    source $config_file
  fi
done

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# load every completion after autocomplete loads
for config_file ($DOTFILES/**/completion.zsh) source $config_file